@Restaurants.API_HostAddress = https://localhost:7153
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3NTAzL2FwaS8iLCJpc3MiOiJyZXN0YXVyYW50cyIsImV4cCI6MTczOTQyMjA1Niwic3ViIjoiZTc4NzIwM2QtM2U0Ny00NmY0LWJiM2EtNzU2OWI3ZjUzMzgyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQURNSU4iLCJOYXRpb25hbGl0eSI6Ikdlcm1hbiIsImlhdCI6MTczOTQyMTE1NiwibmJmIjoxNzM5NDIxMTU2fQ.fkekctP0IU-ppsqhEZMCty3yeZlP4ifNtCkvsyznNh0
 
 

GET {{Restaurants.API_HostAddress}}/api/restaurants?pageNumber=1&pageSize=10&sortBy=Name&sortDirection=Ascending
Authorization : Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurantsB
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Eat Live Laugh",
    "description": "A cozy spot for fresh Pizza.",
    "category": "Italian",
    "contactEmail": "pizza@example.com",
    "contactNumber": "123456789",
    "hasDelivery": false,
    "city": "San Francisco",
    "street": "Market Street",
    "postalCode": "94-103"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Owner Restaurant",
    "description": "A popular place for gourmet burgers.",
    "category": "Japanese",
    "contactEmail": "owner@gmail.com",
    "contactNumber": "0120937812389",
    "postalCode": "90-028"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/23
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "OptimiusPrime",
  "description": "Come get some"
}

###
PUT {{Restaurants.API_HostAddress}}/api/restaurants/23
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "23",
  "name": "doraemon123",
  "description": "Come get some"
}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Dish Name",
    "description": "Dish Description",
    "price": 9.99,
    "kiloCalories": -1
}

###

@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes
Authorization : Bearer {{token}}

###

@dishId=1
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes/{{dishId}}
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner3S@gmail.com",
  "userName": "doraemon123",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identities/login
Content-Type: application/json

{
  "email": "student1@example.com",
  "password": "Password1!"
}
###
POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail": "owner@gmail.com",
  "roleName": "Owner"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{

}
###

GET {{Restaurants.API_HostAddress}}/api/users
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###
