@Restaurants.API_HostAddress = https://localhost:7153
@token = CfDJ8IGx6C_J58VGnHAzo-b4N4pQeCMj-NsCB85zLeH8YYIIyxFiUbgPB32V-Wuy9-_HrHeq7qv0ZIPgyauDH4udYQk-ZNJDrNHACUCMFUo5BB6xfnBJ_pW-4aaWFBwlNBN_wYg59OiP8yiQ54c4Fo2ceq8ZEaoa0GRzQlvV70KzKhGpOE66Egb_VOxgopzi1da1llb0XJPD0TOWT5zhVcn-6ea_M4DuxNhfaDFvLxzgKi7EUCTytfTcMkiZwGs8IEdD-u0Q9r9DqEeMF65Vv74DKiYQibhW4FO7oqqC0nuEuLc8K6Hs-UCjiwSN-sWETWr5nBOKnRnO1tkP2L6EpRiOWyBUaYY6WhPK6SPvCEx1ORuISuBkAeyMT0Bs30eVCLbafkjMY8WfILAakQPSWULM5kvNAD68jO8WfFqaX7zL0M5x_nCwBV12xYouiZlsW5NuEPebePPy-vacDjeMrjabQv9dJpMu9cAFPYBEQP5L5qjSZV2k-xaRqdIciBKRUDGsuUMajFNG84cPQZ2x9qxQJlUVbpXU_KS9d_6ONwTX7MTo1hKF9LJE6yhaLvCJi7gTy8rEQ5bxuvQnM96d_7GwbQu-WTn1rfF5yCZorQ9kdWF82ClqygUQ-rc2N-q2ZkOWyG-3eIrCUH90FoGqBZi9BCDYfB9Ot0f5VGIZmXuBA047GNfNi8UzPKkKoeI9-T1va0c8N-QBUh6zxHw2Z4vtt7YlrSuXBX0JIUHOtREEcojF5wDZs-AseEqJhYbH8HzwES7tCbUI0a4qMsv_sJuWoMxFV8a8ROaeDLR0AxJItCFLofY47NWa-SBMhgWXZkbcWMvDXt3tSOYkv7Zwkt2U4IsbrTkMxXGAlvXkQgjeoN9S2w1BjLzL3AAbL8CqlkpJfg
 
 
 
 
 
GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Sushi Place",
    "description": "A cozy spot for fresh sushi.",
    "category": "Japanese",
    "contactEmail": "sushi@example.com",
    "contactNumber": "123456789",
    "hasDelivery": false,
    "city": "San Francisco",
    "street": "Market Street",
    "postalCode": "94-103"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Owner Restaurant",
    "description": "A popular place for gourmet burgers.",
    "category": "Japanese",
    "contactEmail": "owner@gmail.com",
    "contactNumber": "0120937812389",
    "postalCode": "90-028"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "HolyMoly",
  "description": "Come get some"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Dish Name",
    "description": "Dish Description",
    "price": 9.99,
    "kiloCalories": -1
}

###

@restaurantId=2
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes
Authorization : Bearer {{token}}

###

@dishId=3
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes/{{dishId}}
Authorization : Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "Password1!"
}
###
POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail": "user@gmail.com",
  "roleName": "User"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{

}
###
